### ISSUE TITLE
关于博客 | ZZSHUB

### ISSUE THREAD

**Issue by ZzzzzzS** [ZzzzzzS/ZzzzzzS.github.io#37]
https://blog.zzshub.cn/about/ 

 刚刚终于建立了站点  刚刚终于基本建立了这个博客。博客是采用hexo框架托管在github page上面的.首先感谢Mrminfive无私贡献的skapp主题模板。   网站自动化构建状态 建站更新 2020年7月26日  修改博客主题到butterfly  2018年11月7日  构建出完整的编译工具链,在iPad Pro上更新博客  2018年5月2日  添加数学公式支持  2018年4月25

**Comment by bassomillo** [comment]
顺哥牛逼啊
